# Generated by Django 5.2.6 on 2025-10-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='codigo_agendamento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
