# Generated by Django 5.2.6 on 2025-11-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='tipo_sala',
            field=models.CharField(choices=[('Sala de Reunião', 'Sala de Reunião'), ('Sala de Trabalho', 'Sala de Trabalho'), ('Sala de Videochamada', 'Sala de Videochamada'), ('Sala de Brainstorming', 'Sala de Brainstorming'), ('Sala Genérica', 'Sala Genérica')], max_length=30),
        ),
    ]
